import { Exo_2 } from "next/font/google";
import "./globals.css";


const font = Exo_2({ subsets: ["cyrillic"], weight: '400' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={font.className}>{children}</body>
    </html>
  );
}
